//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Iglesia
    {
        public int Id_Iglesia { get; set; }
        public string Sexo_DP { get; set; }
        public string Apellidos_DP { get; set; }
        public string Nombres_DP { get; set; }
        public Nullable<System.DateTime> FechaNacimiento_DP { get; set; }
        public Nullable<System.DateTime> PaisNacimiento_DP { get; set; }
        public string CiudadNacimiento_DP { get; set; }
        public string PaisResidenciaActual_DP { get; set; }
        public string CiudadResidneciaActual_DP { get; set; }
        public string Direccion_DP { get; set; }
        public string Telefono_DP { get; set; }
        public string Celular_DP { get; set; }
        public string Correo_DP { get; set; }
        public string TipoIdentidad_DP { get; set; }
        public string DocumentoIdentidad_DP { get; set; }
        public string EstadoCivil_DF { get; set; }
        public string NombrePareja_DF { get; set; }
        public string Hijos_DF { get; set; }
        public string NoHijos_DF { get; set; }
        public string Profesion_DL { get; set; }
        public string OcupacionActual_DL { get; set; }
        public string NombreEmpresa_DL { get; set; }
        public string EmpresaTelefono_DL { get; set; }
        public Nullable<System.DateTime> FechaConvencion_DE { get; set; }
        public Nullable<System.DateTime> FechaBautismo_DE { get; set; }
        public Nullable<System.DateTime> FechaAceptado_DE { get; set; }
        public string Denominacion_DE { get; set; }
        public string NombreIglesiaActual_DE { get; set; }
        public string IglesiaMenorTiempo_DE { get; set; }
        public string IglesiaAnterior_DE { get; set; }
        public string PastorActual_DE { get; set; }
        public string SidoDisciplenado_DE { get; set; }
        public string DisciplinaVeces_DE { get; set; }
        public string DisciplinaCausas_DE { get; set; }
        public string FuncionesOcupadaActural_DE { get; set; }
        public string MinisteriosAnteriores_DE { get; set; }
        public string MinisteriosMayorFruto_DE { get; set; }
        public string MinisteriosMayorFrutoPorque_DE { get; set; }
        public string MinisterioLlamado_DE { get; set; }
        public string MetasVida_DE { get; set; }
        public string RespaldoIglesia_DE { get; set; }
        public string NivelEstudio_DA { get; set; }
        public string VezEspulsado_DA { get; set; }
        public string VezEspulsadoPorque_DA { get; set; }
        public Nullable<int> Usuario_Id { get; set; }
        public string PaisNacimiento_DP1 { get; set; }
        public byte[] Foto { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
